### PR TITLE
enhancement(api, PokeCTX): custom errors and keys

### LINKED ISSUE #18: catch unknown pokemon
when 
`$ catch eblochu`
program shouldn't crash

### PR DESCRIPTION
**Pull request by Te4nick**
1) Added custom HTTP StatusCode error. Now one can check if error is raised by return code and make more flexible error handling.
2) Fixed  #18  and  #14  accordingly 
3) Enhanced PokeCTX with "Keys" methods allowing one to treat node children keys as return []string value. Also renamed GetDefault methods to GetOrDefault for more readability. Added comments to make things clear.

### CODE REVIEW

File: pkg/pokectx/tree.go [hunk 1]
```diff
@@ -38,3 +38,19 @@ func (n *te4nickNode) get(path ...string) (string, bool) {
 
 	return child.get(path[1:]...)
 }
+
+func (n *te4nickNode) getChildrenNames(path ...string) (childrenNames []string, found bool) {
```
Comment (temerk1n) [inline pkg/pokectx/tree.go:42]: че за тип te4nickNode

Comment (Te4nick) [reply pkg/pokectx/tree.go:42]: Богдан в честь меня недодерево префиксов назвал

Comment (chrxn1c) [reply pkg/pokectx/tree.go:42]: 1:21 не смотрел нихуя, аппрув

**Review by chrxn1c — APPROVED** [review]
